### PR TITLE
stack_data

### PR DESCRIPTION
**Pull request by alexmojaki**
- Replaced inspect.getinnerframes with stack_data
- Moved some code into a subclass of stack_data.FrameInfo to reduce mutating state in TracebackData. The more of this that can be done the better.
- `executing` can now find ast.Name nodes so removed some custom handling for that
- Only store source code in vanilla linecache. I think you got confused somewhere - linecache will happily retrieve lines for fake filenames starting with `<` if it finds the data already in the cache. It just won't bother checking the filesystem for them. Using linecache as a single source of truth is ideal in general and necessary for stack_data and executing. For IDLE, linecache should be monkeypatched rather than getting those lines separately.

### CODE REVIEW

**Comment by aroberge** [comment]
Thank you for doing this; I really wanted to use stackdata.

This is a big change. Before I merge it, while I am sure that you have been careful, can you confirm that 1) you ran the unit tests and, more importantly, 2) you tried running the console with something like "python -m friendly" and confirmed that syntax errors and runtime errors were properly handled?

**Comment by aroberge** [comment]
The automated tests failed apparently because stack_data could not be found.

**Comment by alexmojaki** [comment]
tox passes locally. I don't know the deal with github actions - maybe the cache should check requirements.txt?

I suggest you check for yourself that this fits with your broader ecosystem. I haven't tried to do that or looked into how. More importantly I'm sure this will change how some things look, particularly which context lines it pulls in, so you need to make sure you're happy with it. Ideally write all the tracebacks produced by the tests to some files and then diff between the two versions.

**Comment by aroberge** [comment]
Ok, I will attempt to merge.

Regarding traceback comparisons: I have a bat file that runs all the tests (with all Python versions) creating tracebacks that are part of the documentation.  This is created locally and I then check it, looking for changes (expected and unexpected...), and then upload it to the documentation site; see for example https://friendly-traceback.github.io/docs/tracebacks_en_3.9.html

**Comment by alexmojaki** [comment]
lol i was expecting you to do that check before merging, not after. hope it works out!

**Comment by aroberge** [comment]
I don't know how to run tests without merging. I figured that, in the worst case scenario, I could revert the merge.

All the tests passed for Python 3.6 to 3.9.  There is at least one test failing for Python 3.10 (after 312 had passed, out of approximately 324).

SyntaxError cases seem to work correctly in the console. However, runtime errors are not captured properly (which is the reason I had my own source cache version in addition to linecache).
```
>>> a = cos(Pi)

Traceback (most recent call last):
  File "<friendly-console:5>", line 1, in <module>

NameError: name 'Pi' is not defined

        Did you mean `pi`?

>>> where()

    Exception raised on line 1 of file <friendly-console:5>.

Problem: source of `<friendly-console:5>` is not available
```

**Comment by aroberge** [comment]
The test that failed wth Python 3.10 is https://github.com/friendly-traceback/friendly-traceback/blob/eb5baa883e9ac45adcc8e89abd43b16f2864ed37/tests/runtime/test_attribute_error.py#L194
It is the only test that fails, as I was able to confirm by commenting it out.

**Comment by aroberge** [comment]
I reverted the pull request. As I wrote when I did so:

In addition to having a failing test with Python 3.10 and the loss of source code in the friendly-console, the removal of the special handling of NameError resulted in losing the underlining of the unknown names (see, for example, how "python" is underlined in https://friendly-traceback.github.io/docs/tracebacks_en_3.9.html#custom-name). Furthermore, the number of lines shown in the traceback (answer to "where()") occasionally varied quite significantly.

Still, I am convinced that using stack_data is the way to go.

I'm going to study what was done an reintroduce changes one at a time

**Comment by alexmojaki** [comment]
> the removal of the special handling of NameError resulted in losing the underlining of the unknown names

did you upgrade `executing`?

**Comment by aroberge** [comment]
Ah, it is still at version 0.6.0.  

I will likely specify the minimum version for all of them in requirements.txt in addition to setup.cfg as I have a batch file to upgrade all my virtual environment that make use of requirements.txt.

I will try to reintroduce the changes one at a time tomorrow, making sure that I understand every single line that was changed.

**Comment by alexmojaki** [comment]
OK, so the problem with the console and linecache is:

1. TracebackData calls traceback.format_exception
2. which eventually calls linecache.checkcache for every filename in the stack
3. which removes files from the cache when os.stat fails

I suggest monkeypatching `checkcache` to ignore fake filenames. Maybe also do the same for `updatecache`.

**Comment by aroberge** [comment]
I know that IDLE patches `checkcache` to reinsert lines that are deleted by Python's linecache (https://github.com/python/cpython/blob/3.9/Lib/idlelib/pyshell.py#L122).  I suspect that iPython does something similar.

I prefer to patch linecache.getlines which is also what I do with the "new" friendly.idle version https://github.com/friendly-traceback/friendly/blob/main/friendly/idle/patch_source_cache.py

**Comment by aroberge** [comment]
Hmm ... I an guessing that to work properly with stack_data in all instances, I do need to patch checkcache as I do have one case that does not work with Python 3.10 after adding only the stack_data change.

**Comment by alexmojaki** [comment]
OK I'm testing 3.10 on executing for the first time and encountering other problems, so it'll be a while. I think it's best that you don't think too much about 3.10 support for now, it's still far away.

**Pull request merged**
