### PR TITLE
Revert "stack_data"

### PR DESCRIPTION
**Pull request by aroberge**
Reverts friendly-traceback/friendly-traceback#3

In addition to having a failing test with Python 3.10 and the loss of source code in the friendly-console, the removal of the special handling of NameError resulted in losing the underlining of the unknown names (see, for example, how "python" is underline in https://friendly-traceback.github.io/docs/tracebacks_en_3.9.html#custom-name).  Furthermore, the number of lines shown in the traceback (answer to "where()") occasionally varied quite significantly.

Still, I am convinced that using stack_data is the way to go.

I'm going to study what was done an reintroduce changes one at a time

### CODE REVIEW

**Comment by alexmojaki** [comment]
> I'm going to study what was done an reintroduce changes one at a time

Now that executing and stuff is sorted, did you end up doing everything in the original PR? I know you did some of it (e.g. https://github.com/friendly-traceback/friendly-traceback/commit/533b75e00cfbe1c61848314a3d7b929e9fc308e2). Run into any problems?

**Comment by aroberge** [comment]
As far as I can remember, I reintroduced everything, and things are working out as well as I could have hoped for.

I (initially) had to do a few additions to "protect" against some problems, such as noted on
https://github.com/friendly-traceback/friendly-traceback/blob/eec78864636865cf9d6259812432929532f4941b/friendly_traceback/core.py#L126
and
https://github.com/friendly-traceback/friendly-traceback/blob/eec78864636865cf9d6259812432929532f4941b/friendly_traceback/core.py#L192
although this last one is likely not needed anymore.

And, I have just noticed that I have a whole bunch of commented-out code in that file which I never removed.

**Comment by alexmojaki** [comment]
> Furthermore, the number of lines shown in the traceback (answer to "where()") occasionally varied quite significantly.

This is expected given the way stack_data divides context into pieces rather than individual lines. Did you end up getting used to it?

**Comment by aroberge** [comment]
So far, everything is fine. I suspect that beginners will not write many long multi-line statements, so this should never be a problem.

**Pull request merged**
